name: Deploy to Droplet

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run docker-compose
        working-directory: .
        run: |
          cp docker/docker-compose-example.yaml ./docker-compose.yaml
          export API_KEY=${{ secrets.API_KEY }}
          export API_HOST=${{ secrets.API_HOST }}
          docker-compose up -d
