name: Deploy to Droplet

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy docker-compose
        working-directory: .
        run: |
          cp docker/docker-compose-example.yaml ./docker-compose.yaml

      - name: Stop and remove existing containers
        working-directory: .
        run: |
          docker-compose down

      - name: Run docker-compose
        working-directory: .
        env:
          API_KEY=${{ secrets.API_KEY }}
          API_HOST=${{ secrets.API_HOST }}
        run: |
          docker-compose up -d
